input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/edusmart_academic"
    jdbc_user => "postgres"
    jdbc_password => "${POSTGRES_PASSWORD}"
    statement => "SELECT *, 'etudiants' AS source_table FROM etudiants"
  }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/edusmart_academic"
    jdbc_user => "postgres"
    jdbc_password => "${POSTGRES_PASSWORD}"
    statement => "SELECT *, 'filieres' AS source_table FROM filieres"
  }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/edusmart_academic"
    jdbc_user => "postgres"
    jdbc_password => "${POSTGRES_PASSWORD}"
    statement => "SELECT *, 'classes' AS source_table FROM classes"
  }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/edusmart_academic"
    jdbc_user => "postgres"
    jdbc_password => "${POSTGRES_PASSWORD}"
    statement => "SELECT *, 'inscriptions' AS source_table FROM inscriptions"
  }
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql-42.7.3.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/edusmart_academic"
    jdbc_user => "postgres"
    jdbc_password => "${POSTGRES_PASSWORD}"
    statement => "SELECT *, 'paiements' AS source_table FROM paiements"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{source_table}"
  }
}